name: crdt_server
description: Generic REST server based on Conflict-free Replicated Data Types (CRDTs).
version: 1.0.0
homepage: https://github.com/cachapa/crdt_server

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  crdt: ^1.1.0
  http: ^0.12.0+3
  shelf: ^0.7.5
  shelf_router: ^0.7.1
  shelf_web_socket: ^0.2.3
  web_socket_channel: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
